export enum PresetRuleType {
  ASR = 'Applicability of the Student Rules policies and procedures',
  ACECRS = 'Academic Conduct Essentials and Communication and Research Skills modules',
  ENGLISH_ELIGIBILITY = 'English Eligibility',
  ADMISSIONS = 'Admissions',
  SATISFACTORY_PROGRESS = 'Satisfactory Progress',
  PROGRESS_STATUS = 'Progress Status',
  AWARD_WITH_DISTINCTION = 'Award with Distinction',
  DEFERRALS = 'Deferrals',
  ADDITIONAL_RULES = 'Additional Rules',
  SKILLS = 'Skills',
  KNOWLEDGE_APPLICATION = 'Knowledge Application',
  KNOWLEDGE = 'Knowledge',
  RANKING_AND_SELECTION = 'Ranking and selection for admission',
}
